version: '3.1'


# MongoDB, PostgreSQL, and Redis services
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: mongodb
    ports:
      - "27017:27017"
    #volumes:
    #  - mongodb_data:/data/db

# Define named volumes
#volumes:
#  mongodb_data: {}  

